import type { Metadata } from "next";
import { Geist, Geist_Mono, Arapey } from "next/font/google";
import "./globals.css";

// Load Geist Sans
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Load Geist Mono
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Load Arapey
const arapey = Arapey({
  variable: "--font-arapey",
  subsets: ["latin"],
  weight: "400", // Arapey only supports 400
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${arapey.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
