name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /var/www/evstore-frontend
            mkdir -p /var/www/evstore-frontend
            exit

      - name: Upload build to server
        uses: easingthemes/ssh-deploy@v4.1.9
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote-user: ${{ secrets.USERNAME }}
          server-ip: ${{ secrets.HOST }}
          remote-path: /var/www/evstore-frontend
          local-path: .next
          args: "-r"

      - name: Restart PM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pm2 restart evstore-frontend || pm2 start "yarn start" --name evstore-frontend --cwd /var/www/evstore-frontend
