name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Safe Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Upload build to server
        uses: easingthemes/ssh-deploy@v4.1.9
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SOURCE: .next
          TARGET: /var/www/evstore-frontend/.next
          ARGS: "-r"

      - name: Restart PM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pm2 restart evstore-frontend || pm2 start "yarn start" --name evstore-frontend --cwd /var/www/evstore-frontend
